### ISSUE TITLE
compression.compress: missmatch between docs and actual implementation

### ISSUE THREAD

**Issue by gagantrivedi** [scikit-mobility/scikit-mobility#111]
According to the docs  

> skmob.preprocessing.compression.compress(tdf, spatial_radius_km=0.2) 
Trajectory compression.
Reduce the number of points in a trajectory for each individual in a TrajDataFrame. All points within a radius of spatial_radius_km kilometers from a given initial point are compressed into a single point that has the median coordinates of all points and the time of the initial point 

which contradicts the actual behavior of the function(i.e: if the min distance between points is less than special_radius_km it returns an empty array) as well as the part of document that follows it, i,e:
 

> spatial_radius_km (float, optional) – the minimum distance (in km) between points of the compressed trajectory.

**Comment by FilippoSimini** [comment]
We'll fix this in release 1.1.2, so that if the minimum distance between all points of a trajectory is less than spatial_radius_km, it returns a compressed trajectory with one point corresponding to the median of all points.

The documentation will be updated as follows:
>     spatial_radius_km : float, optional
>        the minimum distance (in km) between consecutive points of the compressed trajectory. The default is `0.2`.
