### ISSUE TITLE
can you please guide me to run the examples and tutorials given

### ISSUE THREAD

**Issue by praveen4research** [scikit-mobility/scikit-mobility#112]
Hi, 
I am praveen kumar and I have gone through your DITRAS paper and i am interested to work in this area. Hence i had gone through the repositories and trying to run your examples and tutorials, but i am unable to run them. I am new to github and have some basics with Python.
Currently i am using windows 10->anaconda->jupyter notebook.
i also installed github desktop.
whenever i try to run tutorials, it is saying "No module named **skmob**  ".
Hence, i request you to help me in this regard.
Thanking you
![image](https://user-images.githubusercontent.com/54391567/83292735-391f1d80-a208-11ea-840a-060fcff0dccf.png)

![skmob error](https://user-images.githubusercontent.com/54391567/83292719-33293c80-a208-11ea-94fd-55e9d75f7fc4.png)

**Comment by gbarlacchi** [comment]
Hi,

you have to install the skmob package. At the moment, the installation is possible only using the setup.py, please follow the instructions from the Readme (https://github.com/scikit-mobility/scikit-mobility#installation) on how to install the library.
