### ISSUE TITLE
can you please guide me in solving the following problem

### ISSUE THREAD

**Issue by praveen4research** [scikit-mobility/scikit-mobility#113]
i have run the above code twice
in the first attempt i executed the code from "scikit-mobility" folder

in the second attempt, i executed the code from "skmob" folder
i am working in windows 10, anaconda command prompt

![image](https://user-images.githubusercontent.com/54391567/83298582-5953da00-a212-11ea-960c-0325ec75f84c.png)

**Comment by gbarlacchi** [comment]
You have to install the panda package https://pandas.pydata.org/getting_started.html
Whenever you see no module named, it means you have to install that python module.

**Comment by praveen4research** [comment]
Hi,
I thank a lot for you support and immediate reply.
With your support, i am able to solve the above problem
![image](https://user-images.githubusercontent.com/54391567/83336704-3b9a7980-a2d3-11ea-811b-0db4981a3a9a.png)

Now whenever i try to run the tutorial in jupyter note book , it is giving the following error
![image](https://user-images.githubusercontent.com/54391567/83336721-671d6400-a2d3-11ea-9d52-5b3fa7a07e0b.png)
Hence I request you to help me in solving this issue also
Thank you
