### ISSUE TITLE
skmob importing in anaconda prompt, but unable to run in jupyter notebook

### ISSUE THREAD

**Issue by praveen4research** [scikit-mobility/scikit-mobility#114]
Hi,
I thank a lot for you support and immediate reply.
With your support, i am able to solve the earlier problem
![image](https://user-images.githubusercontent.com/54391567/83336811-1a865880-a2d4-11ea-9096-bab329592bc1.png)

Now whenever i try to run the tutorial in jupyter note book , it is giving the following error
![image](https://user-images.githubusercontent.com/54391567/83336818-2d009200-a2d4-11ea-8d48-cd933ab6453f.png)

Hence I request you to help me in solving this issue also
Thank you

**Comment by jonpappalord** [comment]
your notebook is using the Python 3 environment. You should select the "skmob" conda environment created when you installed the library (see here https://github.com/scikit-mobility/scikit-mobility#installation_conda). You can select it from "Kernel --> Change kernel" in the menu bar.

**Comment by jonpappalord** [comment]
@praveen4research I close this issue, if you did not solve the problem, please re-open it.
