### ISSUE TITLE
Normalization factor in radiation model

### ISSUE THREAD

**Issue by thoffman1** [scikit-mobility/scikit-mobility#115]
@TaylorOshan and I were hoping to clarify the implementation of the normalization factor from Simini (2012, A universal model for mobility and migration patterns) later refined by Masucci (2013, Gravity versus radiation models: On the importance of scale and heterogeneity in commuting flows). There is a factor of T_i included in the normalization of the predicted flows (c.f. equation 4 of Masucci or equation 2 of Simini). However, this does not seem included in radiation.py lines 162-5. Is it included elsewhere or otherwise omitted for another reason?

**Comment by FilippoSimini** [comment]
The current implementation of the radiation model follows Eq.4 of Masucci et al., with `normalization_factor = 1.0 / (1.0 - origin_relevance / total_relevance)`.

$T_i$ is the total outflow from origin $i$ and in the equations it multiplies the probability to give the average flow. 
In `radiation.py` it is `origin_outflow` and multiplies the probability when the output format requested is 'flows_average':
```
 if self._out_format == 'flows_average':
    quantities = np.rint(origin_outflow * probs)
```
