### ISSUE TITLE
A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

### ISSUE THREAD

**Issue by praveen4research** [scikit-mobility/scikit-mobility#116]
Hi all,
While i am trying to install the setup file, i got the following error

" A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable."

Please help me to solve the above problem,

Thank you

**Comment by trakru** [comment]
the issue seems to be the fiona version in the setup.py. try commenting out fiona, geopandas, shapely & geojson in the setup dependencies (basically, all the GIS libraries) and manually install each using conda install <package==version>. that should solve the problem

**Comment by gbarlacchi** [comment]
This might be due to fiona installation. I removed fiona dependency from setup as fiona is already installed trough geopandas. I couldn't reproduce this issue. Please, try with the new setup, if the problem persists, please reopen this issue.
