### ISSUE TITLE
Can you please help me with the for relevance of locations in Globally Constrainted Gravity Model?

### ISSUE THREAD

**Issue by yitao-yu** [scikit-mobility/scikit-mobility#118]
Hi! I'm new to the field and I working on a situation where the relevance of a location might change depending on whether the location serve as an origin or destination. I noticed that in the example the relevance is usually population, is it possible to have two columns in the FlowDataFrame and calls one for the origin's relevance and the other for the destination's relevance in this implementation? (Or should I have two rows in the FlowDataFrame, one for the origin and the other for the destination)

**Comment by FilippoSimini** [comment]
What you ask is not implemented in the current version of the library, but it is something that could be included in future releases.
