### ISSUE TITLE
Installation Issue: Will changing the Fiona version in dependency cause trouble? 

### ISSUE THREAD

**Issue by yitao-yu** [scikit-mobility/scikit-mobility#119]
I'm using python 3.7 with conda. While installing the library, it installed fiona 1.8.6, which throws this error message. 
`A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.`
Note that I have conda installed GDAL. 
I can conda install Fiona, but 1.8.6 is not available, so I installed 1.8.4. 
After changing the dependency requirement(1.8.6 -> 1.8.4), the library was installed. Will that cause any trouble in the future?

**Comment by gbarlacchi** [comment]
Yes, thank for noticing it. We updated the setup.py by removing specific version dependencies, this should solve your problem with conda and future installation problems.
