### ISSUE TITLE
visits_per_time_unit returns strange values

### ISSUE THREAD

**Issue by michelegirolami** [scikit-mobility/scikit-mobility#126]
I tested recenty the `visits_per_time_unit ` function which is expected to return:
                                                 n_visits
datetime
2008-03-22 05:00:00+00:00         2
2008-03-22 06:00:00+00:00         2

I instead now got the following output (`visits_per_time_unit(tdf,time_unit='1h')`)

                                                              n_visits
datetime
2013-01-01 00:01:00 1970-01-01 00:00:00.000002004
2013-01-01 00:02:00 1970-01-01 00:00:00.000001972
2013-01-01 00:03:00 1970-01-01 00:00:00.000001921

The n_visits column contains a date time instead of an integer with the number of visits in the time period (hours in my case). I previouly got the expected output. Any changes?
Thanks!
M

**Comment by jonpappalord** [comment]
Bug fixed, it will be working in next release. Next release is planned for next week.
