### ISSUE TITLE
Add hexagonal tessellation with H3

### ISSUE THREAD

**Issue by gbarlacchi** [scikit-mobility/scikit-mobility#131]
Create a new tiler builder, based on H3, to enable the creation of hexagonal tessellation.

**Comment by bandersen23** [comment]
@gbarlacchi Is this being worked on? Happy to give it a shot if not.

**Comment by gbarlacchi** [comment]
Currently this issue is already taken from another contributor. We are planning to further expand the tessellation module by adding a method to create triangle tessellation. Do you want to contribute to that?

**Comment by jonpappalord** [comment]
we just added the H3TessellationTiler in branch 1.2.x
