### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'xy

### ISSUE THREAD

**Issue by valavakilian** [scikit-mobility/scikit-mobility#133]
Hi and thanks for the great package.
I have a geojson of a random Voronoi tessellation map (where the coordinates are in x,y) and I was trying to use the DensityEPR model on it to generate slaw motion. However I ran into the following issue:

File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/home/vala/.local/lib/python3.7/site-packages/pandas/core/series.py", line 4197, in f
    return func(x, *args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/scikit_mobility-1.0-py3.7.egg/skmob/utils/utils.py", line 335, in get_geom_centroid
AttributeError: 'NoneType' object has no attribute 'xy

I assume this can be both because the coordinates are not lat-long and also the possibility that given the random generated Voronoi polygons, finding the centre is impossible (I assume that some numerical error can cause this).

Any Ideas on how I can address this, ie whether the package can take x,y coordinates or how I can transform these x,y coordinates to proper lat-long ?
Thank you

**Comment by gbarlacchi** [comment]
Yes, the trajectoryDataFrame and FlowDataFrame are supporting only lat,lng coordinates. We have a plan to add supports for generic coordinates, but this would not happen in the next release.

However, your error seems to be related to a problem with your voronoi tessellation. The xy mentioned in the error is from geopandas and it has nothing to do with the lat and lng required by skmob. It looks like you have some NoneType in your geometry column. If you remove them, this error should be solved.

**Comment by valavakilian** [comment]
Thank you for the response.
I transformed the x,y to lon-lat and did some more fixed and got it to work. Do you know if I can just transform the x,y coordinates with 
pyproj using transformer = Transformer.from_crs('epsg:4269', 'epsg:4269')
By any chance. I know this is not  related to the library but I don't any other way to try this package with custom geojson objects.
Thanks a lot for the help
