### ISSUE TITLE
Control time sampling with DensityEPR , How to use equal time steps ?

### ISSUE THREAD

**Issue by valavakilian** [scikit-mobility/scikit-mobility#134]
Is there any way to control the time steps to be equal when using any of the generative models ? If not, is there a way to extrapolate equal time step data from generated data ?

**Comment by FilippoSimini** [comment]
Maybe you could use `pandas.DataFrame.resample` on the generated data? 

See <https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html>
