### ISSUE TITLE
Problem while reading tessellation with geopandas library 

### ISSUE THREAD

**Issue by Ali-Mehrabian-619** [scikit-mobility/scikit-mobility#135]
we run into problem with several devices both on linux and windows whenever we want to read tessellation with geo pandas library. Here is the error:

'/vsimem/980bb28ac633488cb58154a6e751f37e' not recognized as a supported file format.

Is there any way to tackle this issue?

**Comment by gbarlacchi** [comment]
Can you be more precise with this? Since the error is about geopandas, It's not clear how this is related to scikit-mobility.

Did you generate '/vsimem/980bb28ac633488cb58154a6e751f37e' with skmob?

**Comment by Ali-Mehrabian-619** [comment]
To generate models, we need spatial tessellation. While we read the url of tess, we run into error.
Here is the code:

 from skmob.utils import utils, constants
 import geopandas as gpd
 from skmob.models import Gravity
 import numpy as np
 # load a spatial tessellation
 url_tess = >>> url = skmob.utils.constants.NY_COUNTIES_2011
 tessellation = gpd.read_file(url_tess).rename(columns={'tile_id': 'tile_ID'})



gpd.read_file causes the error I mentioned.

**Comment by jonpappalord** [comment]
Note that line `url_tess = >>> url = skmob.utils.constants.NY_COUNTIES_2011` is wrong on the documentation, the correct one is `url_tess = skmob.utils.constants.NY_COUNTIES_2011`, we just changed it on the ReadMe. If with this correction the code still does not work, the problem could be with geopandas. Indeed, we are not able to reproduce your error on our machines.
