### ISSUE TITLE
Include license file in source distribution

### ISSUE THREAD

**Issue by synapticarbors** [scikit-mobility/scikit-mobility#137]
It would be helpful to include the license file in the source distribution. I can put in a PR, but it is unclear if `LICENSE` or `LICENSE.txt` is the correct one to include. Generally this is done either by adding a `MANIFEST.in` or a `setup.cfg` with the appropriate content.

**Comment by pareyesv** [comment]
Please notice that [at this moment](https://github.com/scikit-mobility/scikit-mobility/tree/9290122d62a8e5c55cdc1bd32920c13feac92f3d), there are two license files.

One file mentions Enthought. The other one is the BSD-3 standard license.

**Comment by gbarlacchi** [comment]
Added the MANIFEST.in and removed license.txt. It will be in the release.
