### ISSUE TITLE
docs: syntax error in example from `plot_flows` docstring

### ISSUE THREAD

**Issue by pareyesv** [scikit-mobility/scikit-mobility#145]
https://github.com/scikit-mobility/scikit-mobility/blob/500e7e13769f6719f185930c563d9b20a62078f0/skmob/core/flowdataframe.py#L59

The following should work (I haven't run the tests):

```python
url_tess = skmob.utils.constants.NY_COUNTIES_2011
```

I can do a PR if needed.

**Comment by jonpappalord** [comment]
thanks, @pareyesv, we'll be grateful if you could do the PR.
Best,
Luca

**Comment by pareyesv** [comment]
I proposed a PR. Please let me know if you need any help.

**Comment by pareyesv** [comment]
@gbarlacchi @jonpappalord 
I just proposed the new PR to branch 1.2.x
Let me know if you need anything else.

**Comment by jonpappalord** [comment]
thanks a lot @pareyesv, we accepted your pull request. The correction will be in the next version of the library.

**Comment by pareyesv** [comment]
Thanks @jonpappalord and @gbarlacchi !
