### ISSUE TITLE
Import error because of Panel Pandas

### ISSUE THREAD

**Issue by gbarlacchi** [scikit-mobility/scikit-mobility#156]
Running pytest in the scikit-mobility-1.1.2 there are two errors:

=========================== short test summary info
===========================
ERROR skmob/measures/tests/test_collective.py
ERROR skmob/measures/tests/test_individual.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection
!!!!!!!!!!!!!!!!!!!

They are both related to:
     from pandas import Panel
E   ImportError: cannot import name 'Panel' from 'pandas'
(E:\Anaconda\envs\skmob\lib\site-packages\pandas\__init__.py)

**Comment by miccferr** [comment]
Upgrading to latest Pandas version `pandas==1.2.1` gives the green light on all tests.

Closing the issue.
