### ISSUE TITLE
Cluster name function change

### ISSUE THREAD

**Issue by gbarlacchi** [scikit-mobility/scikit-mobility#158]
clustering.cluster() is a point clustering. Modify the name to make it clearer.

**Comment by jonpappalord** [comment]
@gbarlacchi what is the proper name do you suggest? Could `clustering.cluster_points` be reasonable?

**Comment by jonpappalord** [comment]
`clustering.cluster` is deprecated from version 1.3.2 on. In version 2.1, we will refactor the preprocessing module.
