### ISSUE TITLE
Save fdf.plot_flows output as a PNG

### ISSUE THREAD

**Issue by mehradans92** [scikit-mobility/scikit-mobility#159]
Is there an option to save the output of `fdf.plot_flows` as a png image with a custom dpi?

**Comment by mehradans92** [comment]
Actually I used this code to get a png but I was just wondering if there's an easier way without having to take a screenshot off of the browser. Also, with higher resolutions, the text becomes really small.
```
m = fdf.plot_tessellation(zoom=8)
map_f=fdf.plot_flows(flow_color='#bf0000', flow_weight=0.8, zoom=8, map_f=m).save('mobility_flow.html')
import selenium as webdriver
import time
import os
browser = webdriver.Firefox()
tmpurl='file://{path}/{mapfile}'.format(path=os.getcwd(),mapfile='mobility_flow.html')
browser.get(tmpurl)
browser.set_window_size(2560, 1440)
time.sleep(5)
browser.save_screenshot('mobility_flow.png')
browser.quit()```

**Comment by jonpappalord** [comment]
Hi @mehradans92,
Unfortunately, there is no proficient way to save a folium map into a png.
