### ISSUE TITLE
ValueError in TrajDataFrame.plot_trajectory 

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#16]
If trajectories of a single point are present in `TrajDataFrame.plot_trajectory`, the library launches a ValueError (it should plot a single point, instead)
<img width="803" alt="Screenshot 2019-06-10 19 30 50" src="https://user-images.githubusercontent.com/16466050/59213919-48035f00-8bb6-11e9-862c-4ebe8b15428e.png">

**Comment by FilippoSimini** [comment]
I'm not able to reproduce this error. How did you create `tdf` ?

**Comment by jonpappalord** [comment]
`tdf` created from Geolife data. When I passed a `tdf` with one single point it launched the error above.

**Comment by FilippoSimini** [comment]
This does not seem to be an issue anymore. Closing for now.
