### ISSUE TITLE
Tessellation method

### ISSUE THREAD

**Issue by mauruscz** [scikit-mobility/scikit-mobility#166]
It is stated that various type of tessellation are available, but there only are example for the "squared" geometry 
(e.g. `tilers.tiler.get("squared"...)` ).
It is not clear how to call, for example, the hexagonal tessellation.

**Comment by gbarlacchi** [comment]
In the current version, it is available the squared and the voronoi tessellation. The hexagonal tessellation will be part of the next release (https://github.com/scikit-mobility/scikit-mobility/milestone/2).
