### ISSUE TITLE
The "encoding" argument must be added to TrajDataFrame.from_file

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#17]
Since for some files encoding errors can be launched, an `encoding` argument must be added to the method `TrajDataFrame.from_file`, as done by pandas for the `read_csv` method.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

**Comment by gbarlacchi** [comment]
An encoding argument has been added to the method FlowDataFrame and TrajDataFrame.from_file, so that it can be propagated to read_csv method of Pandas.
