### ISSUE TITLE
KeyError: -1 in clustering.cluster when min_samples>1

### ISSUE THREAD

**Issue by wolkomor** [scikit-mobility/scikit-mobility#172]
In lines 148-149: 
c2mfl = dict([(c[1] ,i) for i ,c in  enumerate(sorted([[len(v) ,l] for l ,v in l02x.items() if **l> -0.5**], reverse=True))])
Since the filtering: l> -0.5 is used, the dictionary doesn't have the key -1, while in line 156:
[c2mfl[k] for k in **labels**] it iterate over labels which I guess contains -1. Either replace labels with c2mfl.keys() or remove the filtering of  l> -0.5.

**Comment by FilippoSimini** [comment]
Fixed in v.1.2.3
