### ISSUE TITLE
Calling the super class in epr.py is not using the parameters 

### ISSUE THREAD

**Issue by paulogonc** [scikit-mobility/scikit-mobility#176]
Hi,

I was wondering by playing with your code, why I'm not seeing any differences by playing with other values of the parameter min_wait_time_minutes which is initialized with 20. So I took a look in your code and I found out, that all inherited classes in epr.py does not take into account the passed parameters like here in the SpatialEPR class:

```
def __init__(self, name='Density EPR model', rho=0.6, gamma=0.21, beta=0.8, tau=17, min_wait_time_minutes=20):
        super().__init__() # <-- missing here the values which needs to be passed to the super class
        self._name = name
```

If I change the code like this:

```
def __init__(self, name='Spatial EPR model', rho=0.6, gamma=0.21, beta=0.8, tau=17, min_wait_time_minutes=20):
        super().__init__(name=name, rho=rho, gamma=gamma, beta=beta, tau=tau, min_wait_time_minutes=min_wait_time_minutes)
```

the new values for the parameter min_wait_time_minutes will be used.

Maybe you can consider that. Thanks and best regards Paulo

**Comment by FilippoSimini** [comment]
Fixed in v.1.2.3
