### ISSUE TITLE
TypeError: not enough arguments for format string in epr.py

### ISSUE THREAD

**Issue by paulogonc** [scikit-mobility/scikit-mobility#177]
Hi,

small issue and simple to fix but occurs with python 3.9 due to the `%` syntax formatting string, when you turn the logging option on in the `generate(...)` method.

I made the change like this here to use the logging option
```
        if self._log_file is not None:
            # logging.info('EXPLORATION to %s (%s, %s)' % (location, self.lats_lngs[location])) <-- gives a error
            logging.info(f'EXPLORATION to {location} ({self.lats_lngs[location]})') 
```

**Comment by FilippoSimini** [comment]
Fixed in v.1.2.3
