### ISSUE TITLE
tessellation.tilers.tiler.get function returns a different tessellation in different executions

### ISSUE THREAD

**Issue by cardiamc** [scikit-mobility/scikit-mobility#178]
Good evening,
I run the same function `tilers.tiler.get("squared", base_shape="Manhattan, New York City, USA", meters=1500)` in different days.
Up to yesterday, it returned a tessellation with 78 tiles:
![image](https://user-images.githubusercontent.com/22375674/114315159-df60d280-9afd-11eb-8512-2a0972762a16.png)
This morning, I run the same function, but it returned a different tessellation, with 103 tiles:
![image](https://user-images.githubusercontent.com/22375674/114315212-2f3f9980-9afe-11eb-8de5-9d151d8131fd.png)

As it is possible to observe, now the tessellation includes some areas that were not covered before.

**Comment by jonpappalord** [comment]
Unfortunately, this is a problem of the service `tilers.tiler.get` (i.e., `nominatim` of openstreetmap). There's no way to solve it from our side. We suggest to save the tessellation or the use an existing shape describing the region of interest to `tilers.tiler.get`.
