### ISSUE TITLE
Error in plot_steps if leaving_datetime is not present

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#18]
If the column `leaving_datetime` is not present in a TrajDataFrame, the method `TrajDataFrame.plot_stops` launches an error. This is presumably because the `leaving_datetime` column is used to generate the information in the tooltip. Simply, if `leaving_datetime` is not present, it must not be added to the tooltip.

**Comment by FilippoSimini** [comment]
Now if the column `leaving_datetime` is not present all trajectory points are displayed (related to #35).
