### ISSUE TITLE
Add method `FlowDataFrame.from_file` and `TrajDataFrame.from_file` in the documentation

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#188]
The method [`FlowDataFrame.from_file`](https://github.com/scikit-mobility/scikit-mobility/blob/e9c32bd1ca51d7fe691ed05db59483e87654a164/skmob/core/flowdataframe.py#L330) is not documented and not present in the official documentation.

**Comment by mauruscz** [comment]
Solved
