### ISSUE TITLE
Stop detection points requires a leave trajectory before classified as stop

### ISSUE THREAD

**Issue by stevegaunt** [scikit-mobility/scikit-mobility#190]
I have defined a stop detection for 100m radius of 5 mins 
    stdf = detection.stops(tdf, min_speed_kmh=5,stop_radius_factor=0.5, minutes_for_a_stop=5.0, spatial_radius_km=0.2, leaving_time=True)

This seems to work quite well for a lot of scenarios, however there a couple which don't get classified as a stop,
These are scenarios where trajectory points never have a next leave trajectory .  
For example, the last 100 trajectories within the tdf are within the same location for longer the 5 mins...  however, because the last trajectory doesn't move, these last 100 points don't get classified as a stop point.

Is this something that should be classed as a stop point.   I guess could use clustering to work this out as a additional step, but it would be nice to have option to be inclusive for stop detection to realise this..

**Comment by j4freeman** [comment]
Could this not be resolved by adding an `or i == lendata - 1` clause to lines 176/177 of detection.py? This seems to resolve this scenario as well as pass the existing tests.

**Comment by gbarlacchi** [comment]
Thanks for this solution. Would you be interested in fixing this with a pull request?

**Comment by stevegaunt** [comment]
@gbarlacchi any ideas regarding timelines as to when the PR would likely get merged?
This would be an awesome fix for me

**Comment by gbarlacchi** [comment]
Thanks @j4freeman for you pull request. Could you make your pull on branch 1.2.x? I can then get merged and release the new version on Sept. 17. Thanks!

**Comment by j4freeman** [comment]
Thanks! Just updated the pull to 1.2.x, let me know if there's anything else!

**Comment by gbarlacchi** [comment]
Thanks! This will be added to the next release.

**Comment by stevegaunt** [comment]
@gbarlacchi is there a new schedule release date for the 1.2.3??

**Comment by gbarlacchi** [comment]
Released w/ v1.3.
