### ISSUE TITLE
KeyError in k_radius_of_gyration

### ISSUE THREAD

**Issue by NinaWie** [scikit-mobility/scikit-mobility#191]
Hi, thanks for maintaining this useful package! 

I tried to use the function `k_radius_of_gyration` and I got a KeyError in this line: https://github.com/scikit-mobility/scikit-mobility/blob/7c50c09adda71338c19dcc03f0e11beb747ca71e/skmob/measures/individual.py#L110

The reason was that my original DataFrame had an index where the number 2 was not in the index, and thus doing `[:k]` as in the line above did not work. I could solve it by resetting the index, but it would probably save people some time if this is done automatically, or if you use `.iloc` in the above line, i.e.
```
top_k_locations = traj.drop_duplicates(subset=[constants.LATITUDE, constants.LONGITUDE]).sort_values(by=['visits', constants.DATETIME, ascending=[False, True]).iloc[:k]
```
Feel free to close otherwise; for me it works now.

**Comment by michelegirolami** [comment]
@NinaWie  could you send me the error log and the `tdf` you used?

**Comment by NinaWie** [comment]
@michelegirolami  I don't know for which tdf the error occured, this was months ago. I also cannot reproduce the error on a synthetic example. Maybe it was due to an old pandas version I was using. Closing this now, thanks anyway.

**Comment by GiulianoCornacchia** [comment]
I can't reproduce the error.

I've created the following `TrajDataFrame` `d0`

<html><body>
<div class="output"><div class="output_area"></div></div><div>



  | userid | datetime | lat | lon
-- | -- | -- | -- | --
0|1059 | 2007-04-05 07:47:02 | 45.474777 | 9.210948
1|1059 | 2007-04-05 08:16:00 | 45.474777 | 9.210948
2|1059 | 2007-04-05 08:44:53 | 45.474777 | 9.210948
3|1059 | 2007-04-05 14:22:54 | 45.474777 | 9.210948
4|1059 | 2007-04-05 17:30:29 | 45.474777 | 9.210948

</div>
</body>
</html>

Then I've created another `TrajDataFrame` `d1` shuffling the index as follows:

<html><body>
<div class="output"><div class="output_area"></div></div><div>



  | userid | datetime | lat | lon
-- | -- | -- | -- | --
0|1059 | 2007-04-05 07:47:02 | 45.474777 | 9.210948
3|1059 | 2007-04-05 08:16:00 | 45.474777 | 9.210948
1|1059 | 2007-04-05 08:44:53 | 45.474777 | 9.210948
2|1059 | 2007-04-05 14:22:54 | 45.474777 | 9.210948
4|1059 | 2007-04-05 17:30:29 | 45.474777 | 9.210948

</div>
</body>
</html>

In the first and in the second `TrajDataFrame` `[:k]` and `.iloc[:k]` produce the same results. Indeed:

```
d0[:3].equals(d1.iloc[:3])
[True]
```
