### ISSUE TITLE
v1.3 built with  1.1.5 pandas dependency

### ISSUE THREAD

**Issue by stevegaunt** [scikit-mobility/scikit-mobility#194]
ideally this needs to be rebuilt against pandas 1.3.3

**Comment by gbarlacchi** [comment]
Which problem do you have?

**Comment by stevegaunt** [comment]
this was the only place I could find where to pull this version from pypi was using skmob 
when doing a pip3 install skmob it pulls down pandas 1.1.5

https://libraries.io/pypi/skmob

compare the dependancies with version 1.2  with Scikit-mobilility it uses pandas 1.3.3

**Comment by stevegaunt** [comment]
@gbarlacchi any updates for the above??  Is there something I can do to re-release with right version of pandas dependancy?

**Comment by GiulianoCornacchia** [comment]
@gbarlacchi Yes, I did. I downgraded pandas to version 1.2.5, and everything seems to work now.

**Comment by stevegaunt** [comment]
Hi, sorry for the late delay
It was basically to do with pandas data frame when setting multiple columns using frame[keys] = values new arrays will replace pre-existing arrays for these keys..  1.1.5 version of pandas throw cast errors...

**Comment by gbarlacchi** [comment]
Fixed, will be made available in the next release.
