### ISSUE TITLE
How to add timestamp (origin and destination) data into the individual mobility network (individual_mobility_network)?

### ISSUE THREAD

**Issue by chancyshah** [scikit-mobility/scikit-mobility#201]
How to add timestamp (origin and destination) data into the individual mobility network (individual_mobility_network)?

**Comment by jonpappalord** [comment]
Hi @chancyshah. To add timestamp information to an origin-destination pair in a mobility network, you can proceed as follows:

- split your `TrajDataFrame` into several TrajDataFrames, each corresponding to a time window
- compute the mobility network using `individual_mobility_network` (you'll obtain one DataFrame per each mobility network)
- add to each DataFrame separately a new column corresponding to the timestamp
- merge the DataFrames so to obtain a mobility network with timestamp
