### ISSUE TITLE
Is it possible to use this library to generate trajectories on a playground?

### ISSUE THREAD

**Issue by fatcatZF** [scikit-mobility/scikit-mobility#209]
Thanks for your great work.

I am working on a project about trajectories modelling on a playground, which can be regarded as a small area(e.g. 100 m2). Is it possible to use this library to generate trajectories of agents on a playground given the social relations between them, e.g. groups of agents ?

**Comment by jonpappalord** [comment]
Hi @fatcatZF. First, consider that, to date, scikit-mobility may be used for trajectories that use geographic reference systems only. 

The library actually *does* contain some trajectory generators. In particular, **STS-EPR** allows generating mobility trajectories *given a social network between agents*. You can instantiate and run the STS-EPR generator using the following code: 

```
ts_epr = STS_epr()

syn_trajectories = sts_epr.generate(start, end, social_graph = social_graph,
                                    spatial_tessellation = spatial_tessellation,
                                    diary_generator = diary_generator,
                                    random_state = 2021, show_progress = True,
                                    relevance_column='relevance')
```

See a full example of how to use it in scikit-mobility [here](https://jovian.ai/giuliano-cornacchia/example-sts-epr) and the scientific paper describing STS-EPR [here](https://www.mdpi.com/2220-9964/10/9/599).
