### ISSUE TITLE
scikit-learn simulator using Naive Bayes

### ISSUE THREAD

**Issue by Carla-33** [scikit-mobility/scikit-mobility#212]
Hi All,
I need AODV Attacks code based on scikit-learn simulator using Naive Bayes classifiers. The kinds attack that I have been used are blackhole and selective forwarding. 
Please help me to find out code. Its an honor for me if anyone please give me source code files.

Regards,

**Comment by michelegirolami** [comment]
Dear @Carla-33 thanks for your feedback. Not sure the kind of attack you are looking for fits among the objectives of the scikit-mobility library. This project implements a mobility analysis library.
