### ISSUE TITLE
adapt access to parameters (e.g., _crs) for versions of pandas > 1.2.5

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#218]
for versions of pandas > 1.2.5, we got an error when accessing to the parameters  of the TrajDataFrame. skmob should adapt to more recent version of pandas.

**Comment by G-DL** [comment]
The AMLD 2020 tutorial, Part 02 - Real-World Mobility Data, returns the following error in the cell that calls filtering.filter on a TrajDataFrame:
AttributeError: 'TrajDataFrame' object has no attribute '_crs'.

This is most likely an instantiation of this same problem. A different method for filtering out points on the basis of speed needs to be used while the issue persists.

**Comment by G-DL** [comment]
After digging a little, it seems that the problem originates from the call to any function that follows this condition:   

> if len(groupby) > 0: 

len(groupby) is greater than 0 whenever is_multi_user(data) returns true, or is_multi_trajectory(data) is true, which happens whenever 'uid' or 'tid' are in the names of the columns of a TrajDataFrame object.

Until this is fixed, a temporary workaround consists of splitting a single TrajDataFrame containing multiple user or trajectory IDs into multiple dataframes, one per trajectory per user, and by making sure that the names of the columns are removed from each generated TrajDataFrame.

**Comment by gbarlacchi** [comment]
Solved in 1.3.1.
