### ISSUE TITLE
Map original trajectory points to the stop points

### ISSUE THREAD

**Issue by dmehrab06** [scikit-mobility/scikit-mobility#219]
After I create `TrajDataFrame` from a set of trajectory points and perform `stay_location`, I want to map the trajectory points to the stop point it was compressed to. Is there a library to do this? Otherwise, I am thinking of mapping each point of `tdf` to it's nearest point in `stdf`. Would that work? Here, `tdf` is the `TrajDataFrame` and `stdf` is the dataframe I obtain after performing `stay_location` on `tdf`

**Comment by jonpappalord** [comment]
Hi @dmehrab06,
If I understand well, you want to split the main trajectory into sub-trajectories and keep track of what points are in which sub-trajectory (i.e., the two stops that compose the sub-trajectory). We aim to add such a functionality in the next version of the library.
