### ISSUE TITLE
Add `jupyter` dependency automatically

### ISSUE THREAD

**Issue by GiulianoCornacchia** [scikit-mobility/scikit-mobility#220]
I think it would be beneficial to install automatically `jupyter` when installing `scikit-mobility`.

**Comment by gbarlacchi** [comment]
I understand this could be beneficial for developers, but that's not a good practice and we should avoid it. Packages installed with scikit-mobility should be strictly functionals to the library, jupyter is an external tool that is not needed to have skmob working.
