### ISSUE TITLE
Jump Lengths for sparse data

### ISSUE THREAD

**Issue by gegen07** [scikit-mobility/scikit-mobility#226]
When dealing with real-world data, I face a specific situation using `jump_lengths` method. Imagine the context where the data is collected every 20 minutes, but sometimes the user monitored can disable the collection, and then we have some sparse data. So, I have data composed of two points that are not consecutive, therefore jump_lengths gives me a wrong distance result. This issue is also problematic when I assign a time threshold between trip location <img src="https://render.githubusercontent.com/render/math?math=i"> and trip location <img src="https://render.githubusercontent.com/render/math?math=i %2B 1">. 

By the way, I think my problem is so specific, but I would like to suggest adding a jump_length for sparse data which can be done by adding a time threshold by consecutive locations. What do you think?

**Comment by gegen07** [comment]
I did something like this:
```python
def _jump_lengths_individual(traj, sparse_datetime=None):
    if len(traj) == 1:  # if there is just one point, no distance can be computed
        return []
    if not sparse_datetime:
        lats_lngs = traj.sort_values(by=constants.DATETIME)[[constants.LATITUDE, constants.LONGITUDE]].values
        lengths = np.array([getDistanceByHaversine(lats_lngs[i], lats_lngs[i - 1]) for i in range(1, len(lats_lngs))])
    else:
        aux = traj.sort_values(by=constants.DATETIME)
        lats_lngs = aux[[constants.LATITUDE, constants.LONGITUDE]].values
        datetimes = aux[[constants.DATETIME]].values

        check_sparsity = lambda prev_pt, curr_pt, prev_datetime, curr_datetime: getDistanceByHaversine(curr_pt, prev_pt) if pd.Timedelta(curr_datetime - prev_datetime) <= sparse_datetime else 0

        lengths = np.array([check_sparsity(lats_lngs[i-1], lats_lngs[i], datetimes[i-1][0], datetimes[i][0]) for i in range(1, len(lats_lngs))])
    
    return lengths
```

It should be ok to open a PR to solve this issue?

**Comment by gbarlacchi** [comment]
@FilippoSimini what do think?

**Comment by jonpappalord** [comment]
Hi @gegen07,
This problem is too specific to be added as a feature in the library. We suggest doing as follows: 
- compute the waiting times and the jump lengths between consecutive points as two additional columns of the `TrajDataFrame`.
- consider only rows where the waiting time is lower than the desired threshold.
