### ISSUE TITLE
Estimating departures from arrivals

### ISSUE THREAD

**Issue by umuss** [scikit-mobility/scikit-mobility#238]
I'm working on a human mobility problem on some data that looks like this:

```
    time;origin;destination;flow
    2020-01-10 00:00:00;A;B;10
    2022-01-10 00:15:00;A;C;20
    2022-01-10 00:30:00;B;D;7
```

There are a list of flows from one area to another every 15 minutes for the whole day. So, a given tuple **(A,B)** may appear more than once in the dataset, but each time with a different timestamp. 

For a given record (t1, A, B, f), **f** (the **flow** column) indicates all the people that were present in **A** in the time range between 00:00 and 06:00 and are present in **B** at a given time **t1**. But, if **t1** is in the 00:00-06:00 range, then **f** indicates people that were present in **A** in the time range between 00:00 and 06:00 of the day before.

I'm trying to estimate an origin-destination matrix on this data. Specifically, I want to estimate, for each 15-minute interval of a given day (00:00, 00:15, ..., 23:30, 23:45), how many people have departed from an origin location and are headed towards a destination location. 

The key difference here is that in this case the people have not arrived at the destination, they have only departed. While in my original dataset, each record details the people that have already arrived in the destination area. In some way, the source dataset details the arrivals, while I have to estimate the departures. Like this:

```
    time;origin;destination;deps
    2020-01-20 00:00:00;A;B;5
    2022-01-20 00:15:00;A;C;50
```

The first record says "on the 20th of january at midnight, five people departed from A and were headed to B."

How can I do it? I also have the mean travelling times in second for each (origin, destination) couple for each 1-hour interval of the day. It's in another csv containing records of the type (origin, destination, time_range, travel_time). So I have records such as (A, B, 00:00-01:00, 560) or (B, C, 04:00-05:00, 343). Maybe this could help?

**Comment by jonpappalord** [comment]
Hi @umuss,
A `FlowDataFrame` may have as many columns as needed, but there's no direct way to make this computation using skmob's functionalities.
