### ISSUE TITLE
Fatal error in Github Desktop on checkout

### ISSUE THREAD

**Issue by anitagraser** [scikit-mobility/scikit-mobility#26]
Trying to checkout the repo on Windows using Github Desktop. I think the '.' directory in the docs is the issue: 

![skikit-mobility-checkout-error](https://user-images.githubusercontent.com/590385/61168872-cad05e80-a554-11e9-976e-3e9a5c8f6ba5.PNG)

**Comment by anitagraser** [comment]
As discussed on Skype on Thursday, it might be best to move the documentation to a separate repository.

**Comment by gbarlacchi** [comment]
The issue is now solved. The compiled documentation has been moved on a separate branch.
