### ISSUE TITLE
Timezone Aware? stay_location, home_locations etc

### ISSUE THREAD

**Issue by cachatj** [scikit-mobility/scikit-mobility#275]
Hello scikit-mob devs - it is unclear if we should be passing timezone aware timestamps into several of scikit-mob's core functions like - `home_location` or `stay_locations` . Given these events, especially `home_location` is based on a duration stayed between say 7pm to 7am - should we be passing a timezone aware timestamp to this function, or do we pass it UTC and it converts from there?

Thank you.

**Comment by jonpappalord** [comment]
To address this concern, it's recommended to provide timezone-aware timestamps, as scikit-mobility doesn't automatically convert from UTC. You can use the function [timezone_conversion](https://github.com/scikit-mobility/scikit-mobility/blob/master/skmob/core/trajectorydataframe.py#L884C20-L884C20) for this purpose.
