### ISSUE TITLE
Computing the location clusters on a group of individuals

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#32]
Currently the function `preprocessing.clustering.cluster` computes the location clusters for each individual separately. A useful enhancement would be to give the user the possibility to compute the clusters on a group of individuals (specified in input as, for example, a list of uids). 

(This issue was raised by students during a lesson at the master in Big Data analytics.)

**Comment by FilippoSimini** [comment]
This is already possible. 
To cluster the stop locations of all users, just drop the `uid` column before doing the clustering:
```
stdf = detection.stops(tdf)
stdf = stdf.drop(columns=['uid'])
cstdf = clustering.cluster(stdf)
```

**Comment by jonpappalord** [comment]
Yes, it is possible to do it by removing the `uid` from the TrajDataFrame, but it is not a very elegant solution, especially because it implies the creation of a new TrajDataFrame and hence a waste of memory space. It would be more user friendly to provide an argument where one can specify that the clustering is global.

(Again, suggestion from the audience of students)

**Comment by FilippoSimini** [comment]
what about
```
clustering.cluster(stdf.drop(columns=['uid']))
```

Btw, elegance is a matter of taste! ;)
