### ISSUE TITLE
bug in to_flowdataframe

### ISSUE THREAD

**Issue by FilippoSimini** [scikit-mobility/scikit-mobility#44]
the TrajDataFrame method `to_flowdataframe` creates non-existent flows: when multiple `uid` and `tid` are present, consecutive rows with different `tid` or `uid` are considered as flows. 

To avoid this mistake, it is necessary to first group by (and not just sort by) uid and tid, then compute the flows and finally aggregate.

**Comment by jonpappalord** [comment]
solved, it will work from next release.
