### ISSUE TITLE
FlowDataFrame: get_geometry method

### ISSUE THREAD

**Issue by mascaretti** [scikit-mobility/scikit-mobility#48]
The ```skmob.core.flowdataframe.FlowDataFrame.get_geometry()``` method raises the following:
```Python
AttributeError: 'GeometryArray' object has no attribute 'item'
```

I have obtained this running Notebook 4 (4_flow_models_skmob_tutorial.ipynb) from the tutorial subfolder of this repo.

**Comment by gbarlacchi** [comment]
Thanks, noted. It'll be fixed in the next release.

**Comment by gbarlacchi** [comment]
We are into this issue but we are not able to replicate it. Which version of pandas and geopandas are you using?

**Comment by gbarlacchi** [comment]
replaced item in the code. Please, open again the issue if you are still experiencing this problem.
