### ISSUE TITLE
Gravity.fit does not return attributes noted in docs

### ISSUE THREAD

**Issue by TaylorOshan** [scikit-mobility/scikit-mobility#50]
According to the docs, it looks like the ``fit`` method on the ``Gravity`` class was at some point  [intended to return several attributes](https://github.com/scikit-mobility/scikit-mobility/blob/e3d9bfec7630a3b09148a94fa99cbb86ce649666/skmob/models/gravity.py#L293-#L298) but does not currently return any of them. However, the  ``X`` and ``y`` attributes are explicitly deleted so perhaps docs need to be updated to match current functionality. I would be happy to contribute a PR if the intended functionality could be clarified.

**Comment by gbarlacchi** [comment]
Thank you, noted. We'll fix it the next release.

**Comment by jonpappalord** [comment]
We updated the documentation of the Gravity model: https://scikit-mobility.github.io/scikit-mobility/reference/models.html#skmob.models.gravity.Gravity
In the next release of scikit-mobility (scheduled in January) we'll fix the entire library's documentation.
