### ISSUE TITLE
Why not give the user a Reference Database?

### ISSUE THREAD

**Issue by tiahe66** [scikit-mobility/scikit-mobility#52]
As a new user, I'm little surprised to find that there is no reference to help us to figure what is the true data structure. Could you please update the .gz showed in your 《SCIKIT-MOBILITY: A PYTHON LIBRARY FOR THE ANALYSIS, GENERATION AND RISK ASSESSMENT OF MOBILITY DATA》? 
So that we can know the good tool better.
Thx.

**Comment by gbarlacchi** [comment]
In the folder tutorial we have some reference datasets you can use for testing the library (https://github.com/scikit-mobility/scikit-mobility/tree/master/tutorial/data). Also, as a new user you may find useful to play with the tutorial notebooks in the tutorial folder of this repo. Hope this helps.
