### ISSUE TITLE
Documentation in EPR to fix

### ISSUE THREAD

**Issue by denadai2** [scikit-mobility/scikit-mobility#55]
Dear developers,
I think you have some problems on the documentation (https://scikit-mobility.github.io/scikit-mobility/reference/models.html#module-skmob.models.epr) as the math is not properly shown. Moreover, on line (https://github.com/scikit-mobility/scikit-mobility/blob/master/skmob/models/epr.py#L281) the tessellation is not a dictionary, it requires a geometry inside (geodataframe).

**Comment by jonpappalord** [comment]
We just updated the new documentation for the EPR models: https://scikit-mobility.github.io/scikit-mobility/reference/models.html#skmob.models.epr.DensityEPR
In the new library's release, in January, we'll fix all the other documentation issues.
