### ISSUE TITLE
Add dependencies in README

### ISSUE THREAD

**Issue by madi** [scikit-mobility/scikit-mobility#61]
Could you please add the required dependencies in the README file? Thanks

**Comment by gbarlacchi** [comment]
All the dependecies are specified in the setup.py. Are you facing some particular problem?

**Comment by madi** [comment]
Yes.
`cd opt/scikit-mobility-master/
python3 -m venv skmob
source skmob/bin/activate
python3 setup.py install

[...]
error: pandas 0.24.0 is installed but pandas>=0.25 is required by {'osmnx'}`

**Comment by madi** [comment]
`$ python3 setup.py install
[...]
Processing dependencies for scikit-mobility==1.0
error: pandas 0.24.0 is installed but pandas>=0.25 is required by {'osmnx'}

$ pip3 freeze | grep pandas
geopandas==0.6.2
pandas==0.25.3
`

**Comment by gbarlacchi** [comment]
We removed the dependency from pandas 0.24, which was outdate. You should be able to install osmnx without problems. Please, reopen this issue if the problem persists.
