### ISSUE TITLE
clean non-used libraries and solve the osmnx problem with mybinder

### ISSUE THREAD

**Issue by jonpappalord** [scikit-mobility/scikit-mobility#69]
- Eliminate library `osmnx` (which creates problems with mybinder through RTree). 
- Eliminate `geopy` that is not used 
- Verify if there is another library to read `.gpx` files other than `fiona`

**Comment by FilippoSimini** [comment]
removed dependencies to osmnx and geopy (preprocessing.routing.py is now commented out)
