### ISSUE TITLE
Flow map does not apper

### ISSUE THREAD

**Issue by joselinceron** [scikit-mobility/scikit-mobility#72]
Hi, I am following the tutorial and everything runs perfect, but in "Create a FlowDataFrame"
the code works but the map does not appear 

What can I do?
the cell is in blank, and without any error

**Comment by FilippoSimini** [comment]
Folium returns a blank image if the data to be plotted is too big. 
You can reduce the amount of data to plot using options `min_flow` (chose a high value) of `FlowDataFrame` and `max_users` and `max_points` (choose small values) of `TrajDataFrame`. 
I've added the option `min_flow=20` in tutorial 0.

**Comment by joselinceron** [comment]
thanks, it works
