### ISSUE TITLE
relationship to movingpandas?

### ISSUE THREAD

**Issue by knaaptime** [scikit-mobility/scikit-mobility#83]
Hi, thanks for your work on this package.

Following the discission i just raised [here](https://github.com/anitagraser/movingpandas/issues/54) I'm curious about the overall scope and goals of this project. As in the other issue, it seems that both scikit-mobility and movingpandas are working on implementing space-time geodataframes and I'm curious if there's an opportunity for these proejcts to leverage one another's work

**Comment by jonpappalord** [comment]
The main differences between skmob and moving pandas are the following: 
- skmob one develops a specific data structure (TrajDataFrame, which inherits from the pandas's DataFrame) to manage trajectories while moving pandas uses the GeoDataFrame of geopandas. 
- although skmob may be used for any kind of mobility data, it is tailored for human mobility and implements human-specific mobility measures and generative models.

We have been in contact with the developer of moving pandas and we are discussing whether and how to integrate, at least partially, the two libraries.
