### ISSUE TITLE
Bugs in clustering.cluster

### ISSUE THREAD

**Issue by hong2223** [scikit-mobility/scikit-mobility#87]
When the parameter 'min_samples' in clustering.cluster is set not equal to the default value 1, an error would occur from the return values of '_cluster_array' function in 'clustering.py'.

The error comes from `[c2mfl[k] for k in labels] `: while `-1` exist in `labels` (standing for noise points), it is not a key in the dictionary `c2mfl`, as you removed it during construction.

A possible fix is to separate the situation when `labels == -1`

**Comment by FilippoSimini** [comment]
Thanks, this will be fixed in the next release.
