### ISSUE TITLE
tdf.mapping cannot be used for multi-geometries

### ISSUE THREAD

**Issue by vitekzkytek** [scikit-mobility/scikit-mobility#88]
when using real-world tessellation (in my case EU NUTS-2 levels some of the shapes are not Polygons, but MultiPolygon. 

This leads to error inside the mapping function because `tile_ids` is not assigned (line 313-325 in skmob/core/trajectorydataframe.py )

Is there any reason for it?

**Comment by jonpappalord** [comment]
This issue is the same as #110

**Comment by gbarlacchi** [comment]
Closing, issued solved with #110
