### ISSUE TITLE
Please add support for python 3.8

### ISSUE THREAD

**Issue by r-azh** [scikit-mobility/scikit-mobility#91]
When installing scikit-mobility for python 3.8 it gives an error of :

> Sorry, Python > 3.7 is not supported

**Comment by r-azh** [comment]
I could run scikit-mobility with python 3.8 using following setup:
`from setuptools import setup                                                    
import sys                                                                                              
from setuptools import setup, find_packages                                     

long_description = open('README.md').read()

DEPENDENCIES = ['numpy==1.17.3', 'pandas==0.25.3', 'geopandas==0.6.1', 'scipy==1.4.1', 'powerlaw==1.4.6',
            'tqdm==4.45.0', 'requests==2.22.0', 'scikit-learn==0.22.2.post1', 'statsmodels==0.11.1',
            'folium==0.10.1', 'matplotlib==3.2.1', 'geojson==2.5.0', 'shapely==1.6.4.post2', 'fiona==1.8.11']

TEST_DEPENDENCIES = [
    'hypothesis',
    'mock',
    'python-Levenshtein',
]
                                                                                
long_description = open('README.md').read()                                     
setup(                                                                          
     name='scikit-mobility',                                                     
     version='1.0',                                                              
     packages=['skmob', 'skmob.core', 'skmob.utils', 'skmob.io', 'skmob.measures', 'skmob.models', 'skmob.preprocessing', 'skmob.privacy', 'skmob.tessellation' ],
     license='MIT',                                                              
     python_requires='>=3.6',                                                    
     description='A toolbox for analyzing and processing mobility data.',        
     long_description=long_description,                                          
     maintainer='skmob Developers',                                              
     maintainer_email='gianni.barlacchi@gmail.com',                              
     classifiers=['Intended Audience :: Science/Research',                       
                  'Intended Audience :: Developers',                             
                  'License :: OSI Approved',                                     
                  'Programming Language :: Python',                              
                  'Topic :: Software Development',                               
                  'Topic :: Scientific/Engineering',                             
                  'Operating System :: Microsoft :: Windows',                    
                  'Operating System :: Unix',                                    
                  'Operating System :: MacOS',                                                        
                  'Programming Language :: Python :: 3.6',                       
                  'Programming Language :: Python :: 3.7',                       
                  'Programming Language :: Python :: 3.8',                       
                  ],
     install_requires=DEPENDENCIES                                                             
)`

**Comment by praveen4research** [comment]
i got the following error when i tried to install with the above code
![image](https://user-images.githubusercontent.com/54391567/83295599-dbd99b00-a20c-11ea-83e7-b16719121aca.png)

**Comment by gbarlacchi** [comment]
Skmob now supports Python 3.8, see [#123](https://github.com/scikit-mobility/scikit-mobility/issues/123)
