### ISSUE TITLE
Recommendation for field names

### ISSUE THREAD

**Issue by apiszcz** [scikit-mobility/scikit-mobility#95]
Creating and viewing the data in places other than folium typically considers finding lat,lon or latitude, longitude columns. The name 'lng' is not recognized automatically by QGIS.
Perhaps consider rename to lat,lon or the full word for each attribute of a trajdf.

**Comment by jonpappalord** [comment]
Dear @apiszcz thanks for your suggestion, we'll consider the new field names for the next versions of the library.
